import React from 'react'
import { useState } from 'react'
import FormField from './FormField'
import ShowCase from './ShowCase'

const Home = () => {
  const [imgList, setImgList] = useState(null)
  return (
    <div className='bg-[#f9fafe] h-screen border border-t-slate-200'>
        <div className='pt-8 w-11/12 mx-auto max-w-7xl'>
            <h1 className='font-bold text-3xl'>The Community Showcase</h1>
            <p className='text-slate-500 mt-2'>Browse through a collection of imaginative and visually stunning images generated by DALL-E-AL</p>
        </div>
        <FormField/>
        {!imgList ? <h4 className='pt-4 w-11/12 mx-auto'>No Item to Showcase</h4>:<div className='pt-8 w-11/12 mx-auto grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5 max-w-7xl grid-cols-1'>
          <ShowCase/>
        </div>}
    </div>
  )
}

export default Home